/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveUpload: typeof import('./components/SaveUpload.vue')['default']
    SudanBag: typeof import('./components/SudanBag.vue')['default']
    SudanCharas: typeof import('./components/SudanCharas.vue')['default']
    SudanGlobal: typeof import('./components/SudanGlobal.vue')['default']
    SudanJson: typeof import('./components/SudanJson.vue')['default']
    SudanJsonEdit: typeof import('./components/SudanJsonEdit.vue')['default']
    SudanTagEdit: typeof import('./components/SudanTagEdit.vue')['default']
  }
}
